// SPDX-License-Identifier: GPL-3.0-or-later
// Development probe: official OCIO CPU and GPU processors from one definition.
// Not an application/runtime integration or a redistributable package.
#include "../../src/rendering/ocio/grade.hpp"
#include <array>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <vector>

namespace OCIO = OCIO_NAMESPACE;

using Controls = gp_ocio::Settings;
using gp_ocio::definition;

void write_shader(const OCIO::ConstProcessorRcPtr & processor, const char * file) {
    auto gpu = processor->getDefaultGPUProcessor();
    auto shader = OCIO::GpuShaderDesc::CreateShaderDesc();
    shader->setLanguage(OCIO::GPU_LANGUAGE_GLSL_4_0);
    shader->setFunctionName("applyOcioGrade");
    shader->setResourcePrefix("gp_ocio_");
    shader->setAllowTexture1D(false);
    gpu->extractGpuShaderInfo(shader);
    if (shader->getNumTextures() || shader->getNum3DTextures() || shader->getNumUniforms())
        throw std::runtime_error("Static grade unexpectedly needs GPU resources");
    std::ofstream out(file);
    out << "// Generated by official OpenColorIO 2.4.2; retain OCIO BSD-3-Clause notice.\n"
        "#version 440\nlayout(location=0) in vec2 qt_TexCoord0;\n"
        "layout(location=0) out vec4 fragColor;\n"
        "layout(std140,binding=0) uniform buf { mat4 qt_Matrix; float qt_Opacity; };\n"
        "layout(binding=1) uniform sampler2D source;\n"
        << shader->getShaderText() << "\nvoid main() {\n"
        "vec4 p=texture(source,qt_TexCoord0);\n"
        "vec3 rgb=p.a>0.0 ? p.rgb/p.a : vec3(0.0);\n"
        "rgb=applyOcioGrade(vec4(rgb,p.a)).rgb;\n"
        "fragColor=vec4(rgb*p.a,p.a)*qt_Opacity;\n}\n";
    if (!out) throw std::runtime_error("Cannot write generated preview shader");
}

int main(int argc, char ** argv) {
    try {
        if (argc < 15 || argc > 17) throw std::invalid_argument(
            "Usage: ocio_probe input.f32 output.f32 preview.frag width height repeats b c shadows highlights exposure saturation warmth tint [planar] [baked]");
        bool planar=false,baked=false;
        for (int i=15;i<argc;++i) {
            if (std::string(argv[i])=="planar") planar=true;
            else if (std::string(argv[i])=="baked") baked=true;
            else throw std::invalid_argument("Unknown probe option");
        }
        const long width = std::stol(argv[4]),height=std::stol(argv[5]);
        const long repeats=std::stol(argv[6]);
        if (width<1 || height<1 || width>8192 || height>8192 ||
            width*height>16777216 || repeats<1 || repeats>100)
            throw std::invalid_argument("Probe image/repeat bounds exceeded");
        Controls s{std::stod(argv[7]),std::stod(argv[8]),std::stod(argv[9]),std::stod(argv[10]),
            std::stod(argv[11]),std::stod(argv[12]),std::stod(argv[13]),std::stod(argv[14])};
        auto start = std::chrono::steady_clock::now();
        auto processor = OCIO::Config::CreateRaw()->getProcessor(definition(s));
        auto cpu = baked ? OCIO::Config::CreateRaw()->getProcessor(definition(s,true))->getDefaultCPUProcessor()
                         : processor->getDefaultCPUProcessor();
        const auto prepared=std::chrono::steady_clock::now();
        write_shader(processor,argv[3]);
        const auto shader_done=std::chrono::steady_clock::now();
        std::vector<float> original(static_cast<size_t>(width)*height*4), pixels(original.size());
        std::ifstream input(argv[1],std::ios::binary);
        input.read(reinterpret_cast<char *>(original.data()),original.size()*sizeof(float));
        if (!input || input.peek()!=std::char_traits<char>::eof())
            throw std::invalid_argument("Input must contain exactly width*height RGBA float32 pixels");
        double seconds=0;
        const size_t stride=static_cast<size_t>(width)+7;
        std::array<std::vector<float>,4> planes;
        if (planar) for (auto & plane : planes) plane.resize(stride*height,-123.5f);
        for (long i=0;i<repeats;++i) {
            pixels=original;
            if (planar) for (long y=0;y<height;++y) for (long x=0;x<width;++x)
                for (size_t p=0;p<4;++p) planes[p][y*stride+x]=pixels[(y*width+x)*4+p];
            const auto begin=std::chrono::steady_clock::now();
            if (planar) {
                OCIO::PlanarImageDesc image(planes[0].data(),planes[1].data(),planes[2].data(),
                    planes[3].data(),width,height,OCIO::BIT_DEPTH_F32,sizeof(float),stride*sizeof(float));
                cpu->apply(image);
            } else {
                OCIO::PackedImageDesc image(pixels.data(),width,height,4);
                cpu->apply(image);
            }
            seconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-begin).count();
            if (planar) {
                for (long y=0;y<height;++y) {
                    for (size_t x=width;x<stride;++x) for (const auto & plane : planes)
                        if (plane[y*stride+x]!=-123.5f) throw std::runtime_error("Planar padding changed");
                    for (long x=0;x<width;++x) for (size_t p=0;p<4;++p)
                        pixels[(y*width+x)*4+p]=planes[p][y*stride+x];
                }
            }
        }
        std::ofstream output(argv[2],std::ios::binary);
        output.write(reinterpret_cast<const char *>(pixels.data()),pixels.size()*sizeof(float));
        if (!output) throw std::runtime_error("Cannot write CPU result");
        std::cout << "{\"ocio_version\":\"" << OCIO::GetVersion() << "\",\"cpu_seconds\":"
            << seconds/repeats << ",\"layout\":\"" << (planar?"planar":"packed")
            << "\",\"baked_tone\":" << (baked?"true":"false") << ",\"prepare_seconds\":"
            << std::chrono::duration<double>(prepared-start).count() << ",\"shader_seconds\":"
            << std::chrono::duration<double>(shader_done-prepared).count() << "}\n";
        return 0;
    } catch (const std::exception & e) {
        std::cerr << e.what() << '\n'; return 1;
    }
}
